# Generated by Django 3.1.6 on 2021-02-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
